// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFY5cF8x8B9q9lm41LobwjS-GFq-Zo9vA',
    appId: '1:667178126492:web:2d71a81b3a3d23d0e33159',
    messagingSenderId: '667178126492',
    projectId: 'monitoring-tanaman-tt4c',
    authDomain: 'monitoring-tanaman-tt4c.firebaseapp.com',
    storageBucket: 'monitoring-tanaman-tt4c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4FtF3xOO6smyiQ8XFfUs2HAd3cnnIexk',
    appId: '1:667178126492:android:9deb4fb0adc6802ce33159',
    messagingSenderId: '667178126492',
    projectId: 'monitoring-tanaman-tt4c',
    storageBucket: 'monitoring-tanaman-tt4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3eIe48BR8Rgx_CYmYc99MmlwVS_VlZU8',
    appId: '1:667178126492:ios:619da61b4e13fda8e33159',
    messagingSenderId: '667178126492',
    projectId: 'monitoring-tanaman-tt4c',
    storageBucket: 'monitoring-tanaman-tt4c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3eIe48BR8Rgx_CYmYc99MmlwVS_VlZU8',
    appId: '1:667178126492:ios:619da61b4e13fda8e33159',
    messagingSenderId: '667178126492',
    projectId: 'monitoring-tanaman-tt4c',
    storageBucket: 'monitoring-tanaman-tt4c.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCFY5cF8x8B9q9lm41LobwjS-GFq-Zo9vA',
    appId: '1:667178126492:web:94352c254061cf83e33159',
    messagingSenderId: '667178126492',
    projectId: 'monitoring-tanaman-tt4c',
    authDomain: 'monitoring-tanaman-tt4c.firebaseapp.com',
    storageBucket: 'monitoring-tanaman-tt4c.firebasestorage.app',
  );

}